"""changed anomaly_detector, notification_channels, headers to use strings instead of ints for ids

Revision ID: 1e2499aff043
Revises: 34d5515995b9
Create Date: 2023-04-08 18:14:44.841752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e2499aff043'
down_revision = '34d5515995b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anomaly_detectors', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=8),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=True)

    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=True)

    with op.batch_alter_table('headers', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=8),
               existing_nullable=False)

    with op.batch_alter_table('notification_channels', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=8),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_channels', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(length=8),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('headers', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=8),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('anomaly_detectors', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(length=8),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
