"""remove version from writes

Revision ID: 5e15346f929e
Revises: c359bfd107e4
Create Date: 2023-05-22 17:38:41.540456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e15346f929e'
down_revision = 'c359bfd107e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.drop_column('api_version')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_version', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
