"""add webhook_channel

Revision ID: 6e3e3d358577
Revises: dc8ba8ce7e79
Create Date: 2023-05-29 09:51:22.984831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e3e3d358577'
down_revision = 'dc8ba8ce7e79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_channels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=2048), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_channels', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
