"""add unique constraint for user id and check name

Revision ID: 8bb2089db433
Revises: cbe6cc186509
Create Date: 2023-04-07 19:15:04.110495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bb2089db433'
down_revision = 'cbe6cc186509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_id_name', ['user_id', 'name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_id_name', type_='unique')

    # ### end Alembic commands ###
