"""change check ids to be random strings

Revision ID: 960508765620
Revises: f43b8921bb64
Create Date: 2023-04-08 07:41:10.563158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960508765620'
down_revision = 'f43b8921bb64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=8),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=8),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
