"""remove notification channel from anomaly detector

Revision ID: 9dad8f7bdc4f
Revises: 0f3086f58700
Create Date: 2023-03-11 17:30:34.926338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dad8f7bdc4f'
down_revision = '0f3086f58700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anomaly_detectors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('notification_channel_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anomaly_detectors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_channel_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'notification_channels', ['notification_channel_id'], ['id'])

    # ### end Alembic commands ###
