"""empty message

Revision ID: c9a2209a8265
Revises: 
Create Date: 2023-02-26 16:16:59.569452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9a2209a8265'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_channels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_channels', schema=None) as batch_op:
        batch_op.drop_column('enabled')

    # ### end Alembic commands ###
