"""adding polymorphism for notificaiton channels

Revision ID: cbe6cc186509
Revises: 4212205333aa
Create Date: 2023-04-02 15:50:03.045351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbe6cc186509'
down_revision = '4212205333aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_channels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_channels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('email')

    # ### end Alembic commands ###
