"""empty message

Revision ID: d64a216f93e2
Revises: 9dad8f7bdc4f
Create Date: 2023-03-11 17:34:07.328413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd64a216f93e2'
down_revision = '9dad8f7bdc4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anomaly_detectors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('notification_channel_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anomaly_detectors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_channel_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'notification_channels', ['notification_channel_id'], ['id'])

    # ### end Alembic commands ###
