"""removing status lower bound from error detector

Revision ID: dc8ba8ce7e79
Revises: 5e15346f929e
Create Date: 2023-05-28 12:39:54.260470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc8ba8ce7e79'
down_revision = '5e15346f929e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anomaly_detectors', schema=None) as batch_op:
        batch_op.drop_column('status_lower_bound')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anomaly_detectors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_lower_bound', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
