"""ove url back to HTTPCheck, add url to InfluxDBCheck

Revision ID: f05874de82fd
Revises: ce3470963375
Create Date: 2023-05-08 08:58:42.566067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f05874de82fd'
down_revision = 'ce3470963375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('host', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.drop_column('host')

    # ### end Alembic commands ###
